package com.example.ludoduel.ui.game

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.Build
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import com.example.ludoduel.LudoApp
import com.example.ludoduel.R
import com.example.ludoduel.ui.rememberUiPrefs

/**
 * Plays the game's own short sounds (res/raw, generated by tools/generate_sounds.py, see ASSETS.md)
 * and light vibrations. [soundOn] follows the mute toggle, [vibrationOn] the vibration setting.
 */
class SoundFx(context: Context) : GameFx {
    var soundOn = true
    var vibrationOn = true

    private val pool = SoundPool.Builder()
        .setMaxStreams(6)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()

    private val ids: Map<Sfx, Int> = mapOf(
        Sfx.ROLL to R.raw.sfx_roll,
        Sfx.CLACK to R.raw.sfx_clack,
        Sfx.HOP to R.raw.sfx_hop,
        Sfx.CAPTURE to R.raw.sfx_capture,
        Sfx.HOME to R.raw.sfx_home,
        Sfx.SIX to R.raw.sfx_six,
        Sfx.WIN to R.raw.sfx_win,
        Sfx.LOSE to R.raw.sfx_lose,
        Sfx.CLICK to R.raw.sfx_click,
        Sfx.YOUR_TURN to R.raw.sfx_your_turn,
        Sfx.POP to R.raw.sfx_pop,
    ).mapValues { (_, res) -> pool.load(context, res, 1) }

    private val vibrator: Vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
        (context.getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager).defaultVibrator
    } else {
        @Suppress("DEPRECATION")
        context.getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
    }

    override fun play(sfx: Sfx) {
        if (!soundOn) return
        // Hops repeat quickly, so they are quieter.
        val volume = if (sfx == Sfx.HOP) 0.5f else 0.9f
        pool.play(ids.getValue(sfx), volume, volume, 1, 0, 1f)
    }

    override fun buzz(kind: Buzz) {
        if (!vibrationOn || !vibrator.hasVibrator()) return
        val effect = when (kind) {
            Buzz.ROLL -> VibrationEffect.createOneShot(18, 70)
            Buzz.PICK -> VibrationEffect.createOneShot(12, 60)
            Buzz.EMOJI -> VibrationEffect.createOneShot(20, 60)
            Buzz.CAPTURE -> VibrationEffect.createOneShot(45, 180)
            Buzz.HOME -> VibrationEffect.createWaveform(longArrayOf(0, 30, 60, 40), intArrayOf(0, 140, 0, 200), -1)
        }
        vibrator.vibrate(effect)
    }

    fun release() = pool.release()
}

/** One sound output for the whole app, kept in sync with the mute and vibration settings. */
@Composable
fun rememberAppFx(): GameFx {
    val context = LocalContext.current
    val fx = remember { SoundFx(context.applicationContext) }
    DisposableEffect(fx) { onDispose { fx.release() } }
    val settings = (context.applicationContext as LudoApp).container.settings
    val muted by remember(settings) { settings.muted }.collectAsState(initial = false)
    fx.soundOn = !muted
    fx.vibrationOn = rememberUiPrefs().vibration
    return fx
}
